name: Pylint check

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/*.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/*.py'
  workflow_dispatch:

env:
  python-version: 3.9.12
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python $PYTHON-VERSION
      uses: actions/setup-python@v3
      with:
        python-version: ${{env.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ${context}/build/Dockerfile
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/githubaction:latest